### ISSUE TITLE
Performance of Is_blocked_id is suboptimal

### ISSUE THREAD

**Issue by gabn88** [sqids/sqids-python#24]
Is there any change the performance of this method can be improved, for example by caching the word list?

It now costs about 14 seconds to load 40.000 uids and most time is spend on the is_blocked_id.

**Comment by 4kimov** [comment]
Could you elaborate on "load 40.000 uids"? How do you handle them?

**Comment by gabn88** [comment]
I was profiling an API response that responded with 5000 items, and has 8 relations. We return uids for every relation (instead of pks) as that makes it easier for our developers and hides the number of entries in our database. The total number of uids generated was therefore 40.000 and I found out that simply generating 40.000 uids took 14 seconds. I have now taken out the blocklist and the time spent on generation of the UIDs went back to 4 seconds

**Comment by 4kimov** [comment]
Thanks for elaborating. Makes sense, yeah that's a lot of id generation all at once.

The spec of the library doesn't include internal caching to keep it simple, but it might be a good idea to add caching as a wrapper for your use-case (around the library).

Sorry, I'm not sure what else to recommend, especially since we've had a good bit of [optimizations](https://github.com/sqids/sqids-python/pull/23) added lately. Good job taking out the default blocklist btw.

**Comment by gabn88** [comment]
I totally missed the 0.5.0 release, my numbers were from before this release. Will check it out! Great!
